# Generated by Django 4.2 on 2025-03-03 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paginate_by', models.PositiveIntegerField(default=10, help_text='Số bài viết được hiển thị trên mỗi trang.')),
            ],
        ),
    ]
