# Generated by Django 4.2 on 2025-03-03 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_commentmodel_user_name_commentmodel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='author',
            field=models.CharField(max_length=100),
        ),
    ]
