# Generated by Django 4.2 on 2025-03-03 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_blogmodel_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentmodel',
            name='user',
        ),
        migrations.RemoveField(
            model_name='likemodel',
            name='user',
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='commentmodel',
            name='user_name',
            field=models.CharField(default='Anonymous', max_length=100),
        ),
        migrations.AddField(
            model_name='likemodel',
            name='user_name',
            field=models.CharField(default='Anonymous', max_length=100),
        ),
        migrations.AlterField(
            model_name='blogmodel',
            name='author',
            field=models.CharField(default='Anonymous', max_length=100),
        ),
        migrations.AlterField(
            model_name='blogmodel',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='blog_media/'),
        ),
        migrations.AlterField(
            model_name='blogmodel',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='blogmodel',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
